// gen-compose generates a docker-compose.yml for a simulated Open Inference Mesh cluster.
// Each node gets its own stub-exo sidecar so no real GPU or Exo install is needed.
//
// Usage:
//
//	go run ./tools/gen-compose [flags] > docker-compose.yml
//
// Flags:
//
//	--us       number of US nodes (default 13)
//	--eu       number of EU nodes (default 12)
//	--base-port first host port allocated to node agents (default 8765)
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
)

func main() {
	usCount := flag.Int("us", 13, "Number of US nodes")
	euCount := flag.Int("eu", 12, "Number of EU nodes")
	basePort := flag.Int("base-port", 8765, "First host port for node agents")
	flag.Parse()

	w := os.Stdout

	header(w)
	infrastructure(w)

	port := *basePort
	port = region(w, "us", "coordinator-us", "9000", *usCount, port)
	region(w, "eu", "coordinator-eu", "9001", *euCount, port)

	footer(w)
}

// header writes the compose file preamble and shared anchor.
func header(w *os.File) {
	fmt.Fprint(w, `# Auto-generated by tools/gen-compose — do not edit by hand.
# Regenerate: go run ./tools/gen-compose [--us=N] [--eu=N] > docker-compose.yml

x-oim: &oim
  image: oim-sim
  build: .
  restart: unless-stopped

services:
`)
}

// infrastructure writes the directory and two regional coordinators.
func infrastructure(w *os.File) {
	fmt.Fprint(w, `
  # ── Global directory ───────────────────────────────────────────────────────
  directory:
    <<: *oim
    command: ["/usr/local/bin/oim-directory", "--listen", ":9100"]
    ports:
      - "9100:9100"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9100/health"]
      interval: 3s
      timeout: 2s
      retries: 15
      start_period: 5s

  # ── US pod coordinator ─────────────────────────────────────────────────────
  coordinator-us:
    <<: *oim
    command:
      - /usr/local/bin/oim-coordinator
      - --listen=:9000
      - --pod-id=pod-us
      - --region=us
      - --public-url=http://localhost:9000
      - --directory=http://directory:9100
      - --directory-interval=15
    ports:
      - "9000:9000"
    depends_on:
      directory:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9000/health"]
      interval: 3s
      timeout: 2s
      retries: 15
      start_period: 5s

  # ── EU pod coordinator ─────────────────────────────────────────────────────
  coordinator-eu:
    <<: *oim
    command:
      - /usr/local/bin/oim-coordinator
      - --listen=:9001
      - --pod-id=pod-eu
      - --region=eu
      - --public-url=http://localhost:9001
      - --directory=http://directory:9100
      - --directory-interval=15
    ports:
      - "9001:9001"
    depends_on:
      directory:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9001/health"]
      interval: 3s
      timeout: 2s
      retries: 15
      start_period: 5s
`)
}

// region writes stub-exo + node service pairs for one region.
// Returns the next available host port.
func region(w *os.File, regionName, coordinatorSvc, coordinatorPort string, count, basePort int) int {
	fmt.Fprintf(w, "\n  # ── %s nodes (%d) %s\n",
		strings.ToUpper(regionName), count, strings.Repeat("─", 54-len(regionName)-len(fmt.Sprint(count))-2))

	port := basePort
	for i := 1; i <= count; i++ {
		nodeSvc := fmt.Sprintf("node-%s-%d", regionName, i)
		exoSvc := fmt.Sprintf("stub-exo-%s-%d", regionName, i)
		nodePort := port
		port++

		memGB, latMS, models, capPct, tps := nodeProfile(regionName, i)
		lat, lng := geoForNode(regionName, i)

		// stub-exo service
		fmt.Fprintf(w, `
  %s:
    <<: *oim
    command: ["/usr/local/bin/stub-exo"]
    environment:
      STUB_NODE_NAME: %s
      STUB_MODELS: %s
      STUB_MEMORY_GB: "%d"
      STUB_LATENCY_MS: "%d"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:52415/state"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 3s
`, exoSvc, nodeSvc, models, memGB, latMS)

		// node agent service
		fmt.Fprintf(w, `  %s:
    <<: *oim
    hostname: %s
    environment:
      OIM_INITIAL_TPS: "%.1f"
    command:
      - /usr/local/bin/oim
      - node
      - start
      - --coordinator=http://%s:%s
      - --listen=:%d
      - --exo-url=http://%s:52415
      - --reachability-endpoint=http://%s:%d
      - --region=%s
      - --cap=%.1f
      - --lat=%.4f
      - --lng=%.4f
    ports:
      - "%d:%d"
    depends_on:
      %s:
        condition: service_healthy
      %s:
        condition: service_healthy
`, nodeSvc, nodeSvc,
			tps,
			coordinatorSvc, coordinatorPort,
			nodePort,
			exoSvc,
			nodeSvc, nodePort,
			regionName,
			capPct,
			lat, lng,
			nodePort, nodePort,
			coordinatorSvc,
			exoSvc)
	}
	return port
}

// geoCoord holds an approximate data-center location.
type geoCoord struct{ lat, lng float64 }

// regionCoords are real-ish data-center cities for each region.
// Nodes cycle through them with small per-node jitter so they don't stack on a map.
var regionCoords = map[string][]geoCoord{
	"us": {
		{39.04, -77.49},  // Ashburn, VA (AWS us-east-1)
		{45.52, -122.86}, // Hillsboro, OR (AWS us-west-2)
		{37.34, -121.89}, // San Jose, CA
		{29.42, -98.49},  // San Antonio, TX
		{39.96, -82.99},  // Columbus, OH (AWS us-east-2)
		{41.26, -95.86},  // Council Bluffs, IA (Google)
		{33.19, -80.01},  // Moncks Corner, SC (AWS)
		{40.76, -111.89}, // Salt Lake City, UT
		{41.88, -87.63},  // Chicago, IL
		{33.75, -84.39},  // Atlanta, GA
	},
	"eu": {
		{50.11, 8.68},  // Frankfurt, DE
		{52.37, 4.90},  // Amsterdam, NL
		{53.34, -6.27}, // Dublin, IE
		{48.86, 2.35},  // Paris, FR
		{51.51, -0.13}, // London, UK
		{59.33, 18.07}, // Stockholm, SE
		{40.42, -3.70}, // Madrid, ES
		{52.23, 21.01}, // Warsaw, PL
		{50.85, 4.35},  // Brussels, BE
	},
}

// geoForNode returns a lat/lng for the node with small per-index jitter.
func geoForNode(region string, idx int) (float64, float64) {
	coords := regionCoords[region]
	if len(coords) == 0 {
		return 0, 0
	}
	c := coords[idx%len(coords)]
	// ±0.15° jitter so nodes at the same city don't perfectly overlap
	jitterLat := float64((idx/len(coords))%3-1) * 0.15
	jitterLng := float64((idx/len(coords)+1)%3-1) * 0.15
	return c.lat + jitterLat, c.lng + jitterLng
}

// nodeProfile returns (memGB, latencyMs, modelList, capPct, toksPerSec) for a given node.
// Varies deterministically by region and index to simulate heterogeneous hardware.
func nodeProfile(region string, idx int) (int, int, string, float64, float64) {
	// Memory tiers cycling through nodes: small → medium → large → medium → small …
	memTiers := []int{12, 16, 24, 32, 48, 64, 32, 24, 16}
	memGB := memTiers[idx%len(memTiers)]

	// Latency: US is lower, EU is higher. Add per-node jitter.
	var baseLat int
	if region == "us" {
		baseLat = 120 + (idx%5)*30 // 120–240 ms
	} else {
		baseLat = 220 + (idx%6)*40 // 220–420 ms
	}

	// Model sets: nodes with ≥24 GB run both models; smaller nodes run llama only.
	var models string
	if memGB >= 24 {
		models = "llama-3.2-3b,mixtral-8x7b"
	} else {
		models = "llama-3.2-3b"
	}

	// Cap percentage: larger nodes commit more of their memory.
	var capPct float64
	switch {
	case memGB >= 48:
		capPct = 0.75
	case memGB >= 24:
		capPct = 0.60
	default:
		capPct = 0.50
	}

	// Simulated tok/s scaled to memory tier with per-node jitter.
	tpsBase := map[int]float64{12: 18, 16: 28, 24: 45, 32: 62, 48: 95, 64: 140}
	tps := tpsBase[memGB] + float64((idx%4)*3) // ±9 tok/s jitter

	return memGB, baseLat, models, capPct, tps
}

func footer(w *os.File) {
	fmt.Fprint(w, `
networks:
  default:
    name: oim-mesh
`)
}
