// gen-compose generates a docker-compose.yml for a simulated Open Inference Mesh cluster.
// Each node gets its own stub-exo sidecar so no real GPU or Exo install is needed.
//
// Usage:
//
//	go run ./tools/gen-compose [flags] > docker-compose.yml
//
// Flags:
//
//	--us         number of regular US nodes   (default 22)
//	--eu         number of regular EU nodes   (default 22)
//	--exo-us     number of large exo clusters in US  (default 2)
//	--exo-eu     number of large exo clusters in EU  (default 1)
//	--base-port  first host port allocated to node agents (default 8765)
//	--chaos-pct  per-heartbeat percent chance a node simulates downtime (default 6, 0 disables)
//	--traffic    submit continuous simulated jobs against both coordinators (default true)
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
)

func main() {
	usCount := flag.Int("us", 22, "Number of regular US nodes")
	euCount := flag.Int("eu", 22, "Number of regular EU nodes")
	exoUS := flag.Int("exo-us", 2, "Number of large exo clusters in US (128/256 GB)")
	exoEU := flag.Int("exo-eu", 1, "Number of large exo clusters in EU (128/256 GB)")
	basePort := flag.Int("base-port", 8765, "First host port for node agents")
	chaosPct := flag.Float64("chaos-pct", 6, "Per-heartbeat percent chance a node simulates downtime (0 disables)")
	traffic := flag.Bool("traffic", true, "Include continuous traffic-generator services against both coordinators")
	flag.Parse()

	w := os.Stdout

	header(w)
	infrastructure(w)

	port := *basePort
	port = region(w, "us", "coordinator-us", "9000", *usCount, *exoUS, port, *chaosPct)
	region(w, "eu", "coordinator-eu", "9001", *euCount, *exoEU, port, *chaosPct)

	if *traffic {
		trafficGenerators(w)
	}

	footer(w)
}

func header(w *os.File) {
	fmt.Fprint(w, `# Auto-generated by tools/gen-compose — do not edit by hand.
# Regenerate: go run ./tools/gen-compose [--us=N] [--eu=N] [--exo-us=N] [--exo-eu=N] > docker-compose.yml

x-oim: &oim
  image: oim-sim
  build: .
  restart: unless-stopped

services:
`)
}

func infrastructure(w *os.File) {
	fmt.Fprint(w, `
  # ── Global directory ───────────────────────────────────────────────────────
  directory:
    <<: *oim
    command: ["/usr/local/bin/oim-directory", "--listen", ":9100"]
    ports:
      - "9100:9100"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9100/health"]
      interval: 3s
      timeout: 2s
      retries: 15
      start_period: 5s

  # ── US pod coordinator ─────────────────────────────────────────────────────
  coordinator-us:
    <<: *oim
    command:
      - /usr/local/bin/oim-coordinator
      - --listen=:9000
      - --pod-id=pod-us
      - --region=us
      - --public-url=http://localhost:9000
      - --directory=http://directory:9100
      - --directory-interval=15
    ports:
      - "9000:9000"
    depends_on:
      directory:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9000/health"]
      interval: 3s
      timeout: 2s
      retries: 15
      start_period: 5s

  # ── EU pod coordinator ─────────────────────────────────────────────────────
  coordinator-eu:
    <<: *oim
    command:
      - /usr/local/bin/oim-coordinator
      - --listen=:9001
      - --pod-id=pod-eu
      - --region=eu
      - --public-url=http://localhost:9001
      - --directory=http://directory:9100
      - --directory-interval=15
    ports:
      - "9001:9001"
    depends_on:
      directory:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9001/health"]
      interval: 3s
      timeout: 2s
      retries: 15
      start_period: 5s
`)
}

// region writes stub-exo + node service pairs for one region.
// exoCount large nodes (128/256 GB) come after the regular nodes.
// chaosDowntimePct is the per-heartbeat percent chance each node simulates a
// downtime window (0 disables it) — see agent.Config.ChaosDowntimePct.
// Returns the next available host port.
func region(w *os.File, regionName, coordinatorSvc, coordinatorPort string, count, exoCount, basePort int, chaosDowntimePct float64) int {
	total := count + exoCount
	fmt.Fprintf(w, "\n  # ── %s nodes (%d regular + %d exo) %s\n",
		strings.ToUpper(regionName), count, exoCount,
		strings.Repeat("─", max(0, 46-len(regionName)-len(fmt.Sprint(total))-2)))

	port := basePort
	for i := 1; i <= total; i++ {
		isExo := i > count
		exoIdx := i - count // 1-based index within exo set

		nodeSvc := fmt.Sprintf("node-%s-%d", regionName, i)
		exoSvc := fmt.Sprintf("stub-exo-%s-%d", regionName, i)
		nodePort := port
		port++

		var memGB int
		var latMS int
		var models string
		var capPct, tps float64

		if isExo {
			memGB, latMS, models, capPct, tps = exoProfile(regionName, exoIdx)
		} else {
			memGB, latMS, models, capPct, tps = nodeProfile(regionName, i)
		}
		lat, lng := geoForNode(regionName, i)

		// The first node in each region is a realistic heterogeneous Exo cluster
		// (two Mac Studios + a MacBook Pro) so the dashboard's Node Setup topology
		// diagram is populated out of the box with mixed hardware — its port is the
		// default the "Local agent" bar points at. Other nodes derive device count
		// from memory (one device per ~48 GB).
		deviceCountEnv := ""
		if i == 1 {
			deviceCountEnv = "\n      STUB_DEVICES: \"Mac Studio:32,Mac Studio:32,MacBook Pro:16\""
		}

		// stub-exo service
		fmt.Fprintf(w, `
  %s:
    <<: *oim
    command: ["/usr/local/bin/stub-exo"]
    environment:
      STUB_NODE_NAME: %s
      STUB_MODELS: %s
      STUB_MEMORY_GB: "%d"
      STUB_LATENCY_MS: "%d"%s
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:52415/state"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 3s
`, exoSvc, nodeSvc, models, memGB, latMS, deviceCountEnv)

		// node agent service — exo nodes include --declared-memory-gb so the coordinator
		// sees the correct tier (128/256 GB) even when Docker containers share host RAM.
		declaredMemFlag := ""
		if isExo {
			declaredMemFlag = fmt.Sprintf("\n      - --declared-memory-gb=%d", memGB)
		}
		fmt.Fprintf(w, `  %s:
    <<: *oim
    hostname: %s
    environment:
      OIM_INITIAL_TPS: "%.1f"
      OIM_CHAOS_DOWNTIME_PCT: "%.0f"
    command:
      - /usr/local/bin/oim
      - node
      - start
      - --coordinator=http://%s:%s
      - --listen=:%d
      - --exo-url=http://%s:52415
      - --reachability-endpoint=http://%s:%d
      - --region=%s
      - --cap=%.1f
      - --lat=%.4f
      - --lng=%.4f%s
    ports:
      - "%d:%d"
    depends_on:
      %s:
        condition: service_healthy
      %s:
        condition: service_healthy
`, nodeSvc, nodeSvc,
			tps,
			chaosDowntimePct,
			coordinatorSvc, coordinatorPort,
			nodePort,
			exoSvc,
			nodeSvc, nodePort,
			regionName,
			capPct,
			lat, lng,
			declaredMemFlag,
			nodePort, nodePort,
			coordinatorSvc,
			exoSvc)
	}
	return port
}

type geoCoord struct{ lat, lng float64 }

var regionCoords = map[string][]geoCoord{
	"us": {
		{39.04, -77.49},  // Ashburn, VA (AWS us-east-1)
		{45.52, -122.86}, // Hillsboro, OR (AWS us-west-2)
		{37.34, -121.89}, // San Jose, CA
		{29.42, -98.49},  // San Antonio, TX
		{39.96, -82.99},  // Columbus, OH (AWS us-east-2)
		{41.26, -95.86},  // Council Bluffs, IA (Google)
		{33.19, -80.01},  // Moncks Corner, SC
		{40.76, -111.89}, // Salt Lake City, UT
		{41.88, -87.63},  // Chicago, IL
		{33.75, -84.39},  // Atlanta, GA
		{40.71, -74.01},  // New York, NY
		{47.61, -122.33}, // Seattle, WA
		{39.74, -104.98}, // Denver, CO
		{33.45, -112.07}, // Phoenix, AZ
		{32.78, -96.80},  // Dallas, TX
		{25.77, -80.19},  // Miami, FL
		{42.36, -71.06},  // Boston, MA
		{44.98, -93.27},  // Minneapolis, MN
		{36.17, -115.14}, // Las Vegas, NV
		{39.10, -94.58},  // Kansas City, MO
		{29.76, -95.37},  // Houston, TX
		{36.17, -86.78},  // Nashville, TN
		{39.95, -75.17},  // Philadelphia, PA
		{35.23, -80.84},  // Charlotte, NC
		{47.61, -117.43}, // Spokane, WA
	},
	"eu": {
		{50.11, 8.68},  // Frankfurt, DE
		{52.37, 4.90},  // Amsterdam, NL
		{53.34, -6.27}, // Dublin, IE
		{48.86, 2.35},  // Paris, FR
		{51.51, -0.13}, // London, UK
		{59.33, 18.07}, // Stockholm, SE
		{40.42, -3.70}, // Madrid, ES
		{52.23, 21.01}, // Warsaw, PL
		{50.85, 4.35},  // Brussels, BE
		{45.46, 9.19},  // Milan, IT
		{48.14, 11.58}, // Munich, DE
		{48.21, 16.37}, // Vienna, AT
		{47.38, 8.54},  // Zurich, CH
		{55.68, 12.57}, // Copenhagen, DK
		{60.17, 24.94}, // Helsinki, FI
		{59.91, 10.75}, // Oslo, NO
		{50.08, 14.43}, // Prague, CZ
		{47.50, 19.04}, // Budapest, HU
		{44.43, 26.10}, // Bucharest, RO
		{41.39, 2.16},  // Barcelona, ES
		{45.75, 4.85},  // Lyon, FR
		{53.57, 10.02}, // Hamburg, DE
		{53.48, -2.24}, // Manchester, UK
		{38.72, -9.14}, // Lisbon, PT
		{43.30, 5.38},  // Marseille, FR
	},
}

func geoForNode(region string, idx int) (float64, float64) {
	coords := regionCoords[region]
	if len(coords) == 0 {
		return 0, 0
	}
	c := coords[idx%len(coords)]
	jitterLat := float64((idx/len(coords))%3-1) * 0.12
	jitterLng := float64((idx/len(coords)+1)%3-1) * 0.12
	return c.lat + jitterLat, c.lng + jitterLng
}

// nodeProfile: regular 32 GB contributor nodes — the common case.
func nodeProfile(region string, idx int) (int, int, string, float64, float64) {
	const memGB = 32

	var baseLat int
	if region == "us" {
		baseLat = 110 + (idx%5)*25
	} else {
		baseLat = 200 + (idx%6)*35
	}

	// All 32 GB nodes can run both models.
	models := "llama-3.2-3b,mixtral-8x7b"
	capPct := 0.65
	tps := 62.0 + float64((idx%5)*4) // 62–78 tok/s

	return memGB, baseLat, models, capPct, tps
}

// exoProfile: pooled Exo clusters — 128 GB or 256 GB, high throughput.
// idx is 1-based within the exo set for the region.
func exoProfile(region string, idx int) (int, int, string, float64, float64) {
	var memGB int
	var tps float64
	var models string

	if idx%2 == 1 {
		// 256 GB flagship: runs the full model ladder
		memGB = 256
		tps = 780.0 + float64((idx%3)*20)
		models = "llama-3.2-3b,mixtral-8x7b,llama-3.1-70b,llama-3.1-405b"
	} else {
		// 128 GB mid-tier
		memGB = 128
		tps = 370.0 + float64((idx%3)*15)
		models = "llama-3.2-3b,mixtral-8x7b,llama-3.1-70b"
	}

	var latMS int
	if region == "us" {
		latMS = 80 + (idx%3)*20
	} else {
		latMS = 160 + (idx%3)*30
	}

	capPct := 0.85 // exo clusters commit more capacity
	return memGB, latMS, models, capPct, tps
}

// trafficGeneratorsPerRegion is how many concurrent jobgen instances run
// against each coordinator. jobgen has no internal concurrency (one job at a
// time, then sleep --interval) — a single instance's in-flight window is only
// as wide as one job's latency (~100-200ms), which a 2s SSE snapshot or a
// human glancing at the dashboard will usually miss entirely, making a
// perfectly healthy pod look idle. Running several instances with short,
// staggered intervals overlaps their in-flight windows so the queue/backpressure
// panel shows sustained, visible activity instead of a near-permanent zero.
const trafficGeneratorsPerRegion = 4

// trafficGenerators writes several jobgen services per region that submit
// continuous simulated jobs against coordinator-us and coordinator-eu, so the
// dashboard has live, VISIBLE traffic to render without a human manually
// running jobgen. Submitted anonymously (no --user-id) — this is demo
// traffic, not real account activity.
func trafficGenerators(w *os.File) {
	fmt.Fprint(w, `
  # ── Traffic generators (simulation only — anonymous, no credit accounting) ──
  # Multiple replicas per region with short, staggered intervals so the
  # dashboard's queue/in-flight panel shows sustained visible activity — a
  # single generator's in-flight window is too brief (~100-200ms) to reliably
  # catch on a 2s SSE snapshot or a quick glance at the page.
`)
	writeTrafficGenRegion(w, "us", "coordinator-us", "9000")
	writeTrafficGenRegion(w, "eu", "coordinator-eu", "9001")
	// One pointer-host generator per region: announces as an iOS-style
	// coordination participant and routes its jobs through the encrypted-pointer
	// path, so the dashboards' Security / coordination layer shows a live device
	// with a climbing "pointers served" count out of the box.
	writePointerHostGen(w, "us", "coordinator-us", "9000")
	writePointerHostGen(w, "eu", "coordinator-eu", "9001")
}

func writePointerHostGen(w *os.File, region, coordinatorService, port string) {
	fmt.Fprintf(w, `
  pointer-host-%s:
    <<: *oim
    entrypoint: ["/usr/local/bin/jobgen"]
    command:
      - --coordinator=http://%s:%s
      - --interval=4
      - --model=llama-3.2-3b
      - --pointer-host=ipad-%s-coordinator
    depends_on:
      %s:
        condition: service_healthy
`, region, coordinatorService, port, region, coordinatorService)
}

func writeTrafficGenRegion(w *os.File, region, coordinatorService, port string) {
	for i := 1; i <= trafficGeneratorsPerRegion; i++ {
		intervalSec := 1 + (i-1)%3 // stagger 1s/2s/3s/1s... across replicas
		fmt.Fprintf(w, `
  traffic-gen-%s-%d:
    <<: *oim
    entrypoint: ["/usr/local/bin/jobgen"]
    command:
      - --coordinator=http://%s:%s
      - --interval=%d
      - --model=llama-3.2-3b
    depends_on:
      %s:
        condition: service_healthy
`, region, i, coordinatorService, port, intervalSec, coordinatorService)
	}
}

func footer(w *os.File) {
	fmt.Fprint(w, `
networks:
  default:
    name: oim-mesh
`)
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
